### ISSUE TITLE
Right hand docking?

### ISSUE THREAD

**Issue by natiki** [clineamb/bootstrap-drawer#15]
Hi Caroline,

Great little plugin. Thanks for making it available. I want to use the right aligned option and have run into a small issue. In the screenshots attached:

- Above red line is Firefox 46.0.1
- Below red line is Chrome  50.0.2661.102 m

In both cases the words in the button namely "Special Characters" is not fully displayed. Also it is worth noting that even when there is no vertical scrollbar the same behaviour is in evidence.

What CSS do I have to tweak to get the button to display correctly?

Also a nice feature addition would be to allow the button to be positioned vertically within the browser window. In my case I would prefer to have the button right aligned but in the middle of the display vertically, so that it was not stuck top right as it is now because that is too far away from my content.

![image](https://cloud.githubusercontent.com/assets/4738140/15453466/7b24f788-205a-11e6-8a0b-20313bd6ed92.png)

**Comment by clineamb** [comment]
You'd probably have to add some more custom styles to your button.

**Comment by clineamb** [comment]
You have to probably add some custom styles to your button.  I made the following live changes to my documentation using the Developer Console in chrome: [image on imgur](http://i.imgur.com/iHNlcuz.png)

```css
.your-toggle-btn {
    float: none;
    text-align: right;
}
```

Typically, for these sort of toggle buttons, vertically aligned along the side isn't very common, so I don't think I'd add it as a feature.  However, more CSS can do this for you.  Keep in mind, you button doesn't have to be within the right hand markup and can be anywhere, as long as you hook-up the javascript correctly.  I can help you further if I can see your markup rather than a screenshot.

**Comment by natiki** [comment]
Thanks. I managed to use your suggestion and get the outcome I needed.
