### ISSUE TITLE
close on click outside drawer

### ISSUE THREAD

**Issue by PatrickBK** [clineamb/bootstrap-drawer#3]
Hi,

not sure if this is an issue or a feature request;-) Anyway, considering the way I'd like to use drawer one could call it an issue:-)

Closing drawers when clicking/tapping outside the drawer(s) doesn't seem to work. Is this 'works as designed'? Or am I missing something?

Grtz,

Patrick

btw. check http://beebuy.nl to see my drawer implementation (vind menu and when logged in the user menu)

**Comment by clineamb** [comment]
I did not include clicking outside of the drawer because there are indeed times when drawers won't takeover the entire screen and allow what's "underneath" to be interactive.

What you can do, however, using jQuery and the built-in drawer API is to listen for a click on a large element outside of the drawer, but overlapping the entire body...

For example, let's say you have this sort of markup:

```html
<body class="has-drawer">
    <div class="drawer ...etc..."><!-- drawer mark-up --></div>
   <div class="container"><!-- your page content -->
</body>
```

You can add another drawer "overlay" that goes in-between (and I would also, in the CSS, define the `z-index`es of each of these major containers):

```html
<body class="has-drawer">
    <div class="drawer ...etc..."><!-- drawer mark-up --></div>
    <div class="drawer-close-overlay"></div> 
    <div class="container"><!-- your page content -->
</body>
```

`.drawer-close-overlay` would, by default be `display: none`, and when the drawer becomes opened, show it.  It should cover the entire window, but be layered under the drawer div (so, `position:fixed;` etc.), and then you could listen for a click event on `.drawer-close-overlay` that can call the [drawer javascript api call](http://clineamb.github.io/bootstrap-drawer/javascript.html), `$('.drawer').drawer('hide')`.

You can also essentially do this on the `.drawer-controls` div w/in the drawer markup, just modify it to be the difference in columns (so if your drawer is `.dw-xs-7`, the controls div would be `.dw-xs-5`, for example). You won't need the extra overlay div, since the `.drawer-controls` column is part of the empty space of the drawer.

Let me know if this helps.

**Comment by anupalusoft** [comment]
@clineamb I used to this to close the drawer
    $(document).on('mouseup', function (e) {
            var container = $("drawer");
            if (!container.is(e.target) // if the target of the click isn't the container...
                && container.has(e.target).length === 0) // ... nor a descendant of the container
            {
                container.drawer('hide');
            }
        });

But for the first time when page load it automatically gets open the drawer. It seems like `('hide')` toggle it instead of hiding. 
How can i correct this?

**Comment by clineamb** [comment]
@anupalusoft Make sure you put the hidden class on the drawer itself.   Your code should do the trick, so double check your HTML markup.

**Comment by anupalusoft** [comment]
@clineamb Did it with `if(container.hasClass('open'))`

**Comment by clineamb** [comment]
@anupalusoft great! Let me know if you have any other questions!
