### ISSUE TITLE
Toggle drawer

### ISSUE THREAD

**Issue by th3dark0n3** [clineamb/bootstrap-drawer#4]
jquery "on" binder to click with $(".drawer").drawer("hide")
On the first click in the container the drawer is shown

**Comment by th3dark0n3** [comment]
Okay resolved, used event triggers, and now its working great.

**Comment by clineamb** [comment]
Care to share your fix for future use?  
Anyway I can help to not have to use event triggers?

**Comment by bkwdesign** [comment]
I'm using **bootstrap 3.0.0** - and my drawer was only working "once" but further clicking of the button did not successfully toggle the drawer any more.

A little watching of the DOM through Firebug showed me that it was getting stuck in the transition state and not finishing up properly.

The problem was that your script is listening for a `'bsTransitionEnd'` event - and that is only raised in later revisions of BS 3.x.x, but if I change your code to listen for `transitionend` then it works great with my 3.0.0 installation

**Comment by th3dark0n3** [comment]
$('#drawerExample').on('shown.bs.drawer', function() {
    $(".container").on("click", function() {
        $(".drawer").drawer('hide');
    });
});

So basically only executed when it is shown
